### ISSUE TITLE
Cool, this works, can you further share the detailed C++ functions ? 

### ISSUE THREAD

**Issue by finekewei** [khaled45690/yuv_to_png#1]
Thank you, has star

**Comment by khaled45690** [comment]
Yeah no problem, but i am still working on the C++ code to  add more features if possible , but i grant you it will be shared in the next version to be open source and available for developer to correct my code if needed as well

**Comment by khaled45690** [comment]
you can find the conversion code in this link

https://github.com/khaled45690/yuv_to_png/tree/main/android/src/main/cpp/Conversion

I am open for any contribution for better  conversion rate and increase the conversion success rate to 100%
