### ISSUE TITLE
ld: error: undefined symbol: nv21_to_png(unsigned char*, int, int, int, bool)

### ISSUE THREAD

**Issue by read0nly** [khaled45690/yuv_to_png#2]
I  an error, can you please help me analyze and find a solution? Thank you.

ld: error: undefined symbol: yuv_to_png(unsigned char*, int, unsigned char*, int, int, unsigned char*, int, int, int, bool)
>>> referenced by yuv_to_png.cpp:15 (/Users/jieliu/Downloads/yuv_to_png-0.0.2 (1)/android/src/main/cpp/yuv_to_png.cpp:15)
>>>               CMakeFiles/yuv_to_png.dir/yuv_to_png.cpp.o:(yuvToPng)

ld: error: undefined symbol: nv21_to_png(unsigned char*, int, int, int, bool)
>>> referenced by yuv_to_png.cpp:22 (/Users/jieliu/Downloads/yuv_to_png-0.0.2 (1)/android/src/main/cpp/yuv_to_png.cpp:22)
>>>               CMakeFiles/yuv_to_png.dir/yuv_to_png.cpp.o:(nv21ToPng)
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by khaled45690** [comment]
I am assuming you want to build the cpp code locally,  you are not linking the conversation.h file with your build , to avoid such a thing you could simply take the code from the conversation.cpp and replace it into the libyuv_to_png.cpp file , if you want further help please let me know
